name: Delete old

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
         keep_latest: 0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
