name: Build palen1x (Extended)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, i686, aarch64, armv7 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Install qemu-user-static
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y qemu-user-static
          chmod +x extendedbuild.sh

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          sudo -E ./extendedbuild.sh NIGHTLY

      - name: Prepare artifact
        run: |
          mkdir palen1x
          cp work/*-${{ matrix.arch }}.iso palen1x
          cp work/iso/boot/initramfs.xz palen1x/initramfs-${{ matrix.arch }}.xz
  
      - name: Draft release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: work/*.iso
          
      - name: Release files to github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: extended
          prerelease: true
          name: Latest Extended Palen1x Release
          body: |
           It will take sometime to boot, Don't worry about that.
           NOT RECOMMENDED
          
           palen1x-EXTENDED-amd64.iso: palen1x for 64-bit computers (most people will need this)
           palen1x-EXTENDED-i686.iso: palen1x for 32-bit computers
           palen1x-EXTENDED-aarch64.iso: palen1x for 64-bit ARM computers
           palen1x-EXTENDED-aarch64.iso: palen1x for 32-bit ARM computers
          files: |
            work/palen1x-EXTENDED-amd64.iso
            work/palen1x-EXTENDED-i686.iso
            work/palen1x-EXTENDED-aarch64.iso
            work/palen1x-EXTENDED-armv7.iso
            
            
